"""Test

Revision ID: 2d7cc9d97a32
Revises: 
Create Date: 2024-04-22 18:17:44.294649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7cc9d97a32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authenticated_servers_id', table_name='authenticated_servers')
    op.drop_table('authenticated_servers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authenticated_servers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('server_id', sa.INTEGER(), nullable=True),
    sa.Column('authenticated_by_id', sa.INTEGER(), nullable=True),
    sa.Column('requested_by_id', sa.INTEGER(), nullable=True),
    sa.Column('is_authenticated', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['authenticated_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_authenticated_servers_id', 'authenticated_servers', ['id'], unique=False)
    # ### end Alembic commands ###
